### ISSUE TITLE
[Frontend]: Grid should take all the available space

### ISSUE THREAD

**Issue by alesbe** [alesbe/js-pathfinder#1]
## 🤔 Problem
I made a pathfinder algorithm in JS, and now im trying to implement it in a web app, everything is working as expected for now! But the grid that I did does not fit the parent div, specially when resizing the window. Here is an example:

Fullscreen:
![full](https://i.imgur.com/BAU0uMl.png)

Resized:
![resized](https://i.imgur.com/LugpziT.png)

The light-brown rectangle is the grid where you select squares when dragging the mouse, but as you can see, when I resize the window, the grid does not adapt correctly.

I would like to fill the entire space except the navbar with this grid!

## ✅ Expected behaviour
A single page with a navbar and a grid filling the entire space.

## 📝 Additional information
- The quanity of elements that compose the grid is irrelevant, for now I generated 45 rows with 100 elements, this number can change depending on the window size.
- The cells should be squared (no stretching when window resized!)
- `index.html` contains the HTML, `styles.css` the CSS, and `render.js` everything related to filling the grid with cells!

If you need anything (additional info, any explanation, anything else), just ask! :)

<hr></hr>
Happy hacktoberfest! 🙌

**Comment by raji2004** [comment]
i would love to be assigned this issue

**Comment by alesbe** [comment]
Sure! Let me know if you need anything :)

**Comment by raji2004** [comment]
it said u are not participating in hacktoberfest

**Comment by raji2004** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/105373159/193420141-7eac54b7-7676-44f9-a45b-27cf1f1be5c1.png)

**Comment by alesbe** [comment]
> it said u are not participating in hacktoberfest

yes, I am

![img](https://i.imgur.com/KUyL8tB.png)

**Comment by alesbe** [comment]
I added the label to the repo too, it should be fixed now!

**Comment by raji2004** [comment]
> I added the label to the repo too, it should be fixed now!


nope its not

**Comment by raji2004** [comment]
also im done so please merge

**Comment by alesbe** [comment]
> nope its not

maybe it takes some time to update, i can't do more for now

> also im done so please merge

I added some comments to the PR, if it's too difficult or takes too much time you can leave it don't worry

**Comment by raji2004** [comment]
> > nope its not
> 
> maybe it takes some time to update, i can't do more for now
> 
> > also im done so please merge
> 
> I added some comments to the PR, if it's too difficult or takes too much time you can leave it don't worry

which comments ?

**Comment by alesbe** [comment]
In the pull request, the grid now fills the remaining space, but i wanted to fit the window without overflowing. i think that this change might need some more work to behave as expected. try to solve other issues, i think that i might close this one for hacktoberfest and post easier ones

**Comment by raji2004** [comment]
> In the pull request, the grid now fills the remaining space, but i wanted to fit the window without overflowing. i think that this change might need some more work to behave as expected. try to solve other issues, i think that i might close this one for hacktoberfest and post easier ones

ok i will try my best to not make it overflow but to do it accurately i need the average hieght of each row please

**Comment by alesbe** [comment]
Sure! i thought about resizing each cell to `1vw` height `1vw` width, so each row should be the same height as the cells, in this case `1vw`, but you can try any.

The grid can be actually bigger, but i would like to fit everything in one screen without scrollbars.

If this is tricky, don't worry about it, i was trying to figure out the best approach but i couldnt find the best one

**Comment by raji2004** [comment]
> Sure! i thought about resizing each cell to `1vw` height `1vw` width, so each row should be the same height as the cells, in this case `1vw`, but you can try any.
> 
> The grid can be actually bigger, but i would like to fit everything in one screen without scrollbars.
> 
> If this is tricky, don't worry about it, i was trying to figure out the best approach but i couldnt find the best one

no i actually have a solution which is dividing the screen hieght against the row hieght then making that your nrow value that way there shouldnt be any scrool bar

**Comment by alesbe** [comment]
That's a good idea actually! Im not sure if the navbar could be an issue when calculating the size though

**Comment by raji2004** [comment]
> That's a good idea actually! Im not sure if the navbar could be an issue when calculating the size though

it wont be if your check for the hieght of the div after the nav bar

**Comment by raji2004** [comment]
> That's a good idea actually! Im not sure if the navbar could be an issue when calculating the size though

so should work in the adjustment or i shouldnt worry?

**Comment by alesbe** [comment]
im not sure 😅, if you want you can try! the grid should adapt to the remaining space and the cells should be squared, if it's too difficult dont worry about it :)

**Comment by raji2004** [comment]
> im not sure 😅, if you want you can try! the grid should adapt to the remaining space and the cells should be squared, if it's too difficult dont worry about it :)

But u will still Marge regardless right?

**Comment by alesbe** [comment]
If the PR removes the overflow yes, but i prefer it without scrollbar that's why im saying, if this issue takes too much time to solve feel free to try another one

**Comment by raji2004** [comment]
> If the PR removes the overflow yes, but i prefer it without scrollbar that's why im saying, if this issue takes too much time to solve feel free to try another one

i have done it to the best of my ability now check there shouldnt be a scroll bar

**Comment by alesbe** [comment]
I'm still getting the scrollbar thing :(, maybe is something related to the screen resolution or something.

But I merged because the result wasn't bad and you spent a lot of time, thanks for the contribution!

Happy hacktoberfest :)

**Comment by raji2004** [comment]
> I'm still getting the scrollbar thing :(, maybe is something related to the screen resolution or something.
> 
> But I merged because the result wasn't bad and you spent a lot of time, thanks for the contribution!
> 
> Happy hacktoberfest :)

it still showing not accepted

**Comment by alesbe** [comment]
It takes some time to update i guess, but as you can see, it's accepted and merged, don't worry about it if you can't find an optimal solution, I'll try myself now, but if you write in this issue thread I'll get the notification even if it's closed :)
