### ISSUE TITLE
[Frontend]: Find a pleasing color palette for this project

### ISSUE THREAD

**Issue by alesbe** [alesbe/js-pathfinder#3]
*🚨 Hey! This issue may seem simple, but please, don't take a random palette just to make the contribution, I would appreciate a screenshot of how the palette looks before doing the PR :) 🚨*

## Problem
The default colors are kinda ugly and does not match, here is how it looks right now:
![default](https://i.imgur.com/uHBzhwK.png)

A palette that match together would be much better!

## Solution
Find one or more color palettes that you like for this project (please try the palette before!). If you need inspiration [this](https://colorhunt.co/) website it's great for that. Don't be afraid to try different styles! I actually like the discord color palette, you can try that too!

## Additional notes
- Change the colors using these variables:
https://github.com/alesbe/js-pathfinder/blob/e0db6abeab4304c387f976a2ee67ac2f9ad13f79/css/styles.css#L1-L8

- The colors should match together and be *pleasing* to watch, but make sure that you can differenciate the different nodes easily!

- The webapp is in a very early stage, if you want to try the functionality to check how the colors look, select **Draw mode** to change the modes. Place one *Starting node*, one *Target node*, draw some walls and press **Visualize**

<hr></hr>
Happy hacktoberfest! 🙌🎨

**Comment by Anurag-Singh-04** [comment]
Hey @alesbe I would like to work on this issue, could please assign this to me.

**Comment by alesbe** [comment]
Sure! But I'm not in the computer right now, I'll assign it to you before merging the PR

**Comment by Anurag-Singh-04** [comment]
Do you want to change background colour also?

**Comment by alesbe** [comment]
Yeah, you can try if you want!

**Comment by alesbe** [comment]
@Anurag-Singh-04 Im at home now, do you want me to assign you the issue?

**Comment by darshikaguptaa** [comment]
Hey can you assign this issue to me. I'm interested in working on this

**Comment by Anurag-Singh-04** [comment]
Yes @alesbe you can assign this to me.

**Comment by alesbe** [comment]
@darshikaguptaa @Anurag-Singh-04 hey guys, sorry but I'll wait for the PR to assing the issue to anyone. I experienced a lot of times assigning the issue to anyone and then they don't respond or abandon the PR. Because this is a easy and small issue you can try some suggestions and I'll merge the PR that I like the most!

**Comment by alesbe** [comment]
I'm closing the issue for now, maybe it's to early for deciding the palette, I might reopen it in a more advanced stage, sorry
