### ISSUE TITLE
[Suggestion/Feature]: Selecting a node type changes the navbar text

### ISSUE THREAD

**Issue by odracir02** [alesbe/js-pathfinder#4]
## Suggestion
When you select what you are doing, it will appear on top

![issue](https://user-images.githubusercontent.com/96169228/193855593-93a76b2f-14c5-4a51-acb1-632e357fcb67.PNG)

- [ ] Do you want to solve this issue yourself?

**Comment by alesbe** [comment]
Thanks for the suggestion! That's a really great idea. I'll implement this :)

Happy hacktoberfest! 🙌

**Comment by alesbe** [comment]
If anyone wants to give it a try just say and I'll assign it!

**Comment by odracir02** [comment]
I think i could help you

**Comment by alesbe** [comment]
Fixed this in 4cf04022a62855e29c2b3e36c785bd01689046ed, thanks for the contribution!
